[module]

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "archetypes"
  target = "archetypes"

[[module.mounts]]
  source = "data"
  target = "data"

[[module.mounts]]
  source = "mounted-lfs"
  target = "static/mounted-lfs"

